name: "bluebell"
mode: "dev"
port: 8081
version: "v0.0.1"
start_time: "2020-07-01"
machine_id: 1

auth:
  jwt_expire: 8760

log:
  level: "debug"
  filename: "bluebell.log"
  max_size: 1000
  max_age: 3600
  max_backups: 5

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 12345678
  db: bluebell
  max_open_conns: 100
  max_idle_conns: 20

redis:
  host: 127.0.0.1
  port: 6379
  db: 0